Soma de dígitos
Fimba-Code/blog pull request #19
Opened 2020-05-25 11:34 UTC by stackswithans

This is the first draft of the blog post that talks about the solution to challenge #1 of last week's coding challenge.

2020-05-25 11:58 UTC, Fausto95 approved these changes
Parece-me bem..

2020-05-25 11:58 UTC, Fausto95 commented on content/blog/2020-05-25-soma-de-digitos/index.md
> +author: "Nome do Autor"
Falta o teu nome aqui

2020-05-25 12:02 UTC, brunokiafuka requested changes
Valeu bwé @stackswithans, só algumas coisinhas para que possamos fazer o merge. 

1. A view das ordered list (mas isso podemos fix rápido), creio que é um problema no style. (don't worry about it).
2. O artigo tem em falta um algorithm que mostre como a solução foi conceptualised, temos apenas como as soluções possíveis etc..., o que seria benéfico era escrever mesmo um algorithm seguido de uma explicação compreensiva. Exemplo:

```sh
var
 numeroA, numeroB : inteiro
    
1. inicio
  2.escreva("Numero A? ")
  3. leia(numeroA)
  4. escreva("Numero B? ")
  5. leia(numeroB)
  6. escreva("Soma A + B = ", numeroA + numeroB)
7. fim
```

E depois explicas num bloco abaixo.

2020-05-25 12:02 UTC, brunokiafuka commented on content/blog/2020-05-25-soma-de-digitos/index.md
> +author: "Nome do Autor"
@stackswithans, tens de add o teu name.

2020-05-25 12:02 UTC, brunokiafuka commented on content/blog/2020-05-25-soma-de-digitos/index.md
> +```python
remove comments from code example.

2020-05-25 12:02 UTC, brunokiafuka commented on content/blog/2020-05-25-soma-de-digitos/index.md
> +#### Resto da divisão por 10
remove `###` and simply make string bold `**my string**`

2020-05-25 13:08 UTC, stackswithans commented on content/blog/2020-05-25-soma-de-digitos/index.md
> +author: "Nome do Autor"
vu mudar já

2020-05-25 13:42 UTC, stackswithans commented on content/blog/2020-05-25-soma-de-digitos/index.md
> +author: "Nome do Autor"
Nas explicações de cada solução tentei introduzir um pequeno algoritmo, será que têm que estar obrigatoriamente em PORTUGOL?

2020-05-25 13:47 UTC, brunokiafuka commented on content/blog/2020-05-25-soma-de-digitos/index.md
> +author: "Nome do Autor"
use mesmo o PORTUGOL, para facilitar na leitura do artigo.

2020-05-26 08:33 UTC, brunokiafuka approved these changes
LGMT 🚀 @stackswithans

2020-05-26 08:44 UTC, merged